rm -rf llt/ops/llt_new/stub/common
rm -rf llt/ops/llt_new/stub/framework
mkdir -p llt/ops/llt_new/stub/common/register/scope
mkdir -p llt/ops/llt_new/stub/common/graph/utils
mkdir -p llt/ops/llt_new/stub/framework/domi/common/ge
mkdir -p llt/ops/llt_new/stub/framework/domi/common/model_parser
mkdir -p llt/ops/llt_new/stub/framework/domi/common/op
mkdir -p llt/ops/llt_new/stub/framework/domi/common/helper
mkdir -p llt/ops/llt_new/stub/framework/domi/common/auth
mkdir -p llt/ops/llt_new/stub/framework/domi/common/convert
mkdir -p llt/ops/llt_new/stub/framework/domi/common/context
mkdir -p llt/ops/llt_new/stub/framework/domi/model
mkdir -p llt/ops/llt_new/stub/framework/domi/graph/common
mkdir -p llt/ops/llt_new/stub/framework/domi/graph/passes
mkdir -p llt/ops/llt_new/stub/framework/domi/parser/common
mkdir -p llt/ops/llt_new/stub/framework/domi/parser/tensorflow
mkdir -p llt/ops/llt_new/stub/framework/domi/parser/tensorflow/scope
mkdir -p llt/ops/llt_new/stub/framework/domi/parser/common/op_def
cp common/graph/utils/tensor_utils.cc llt/ops/llt_new/stub/common/graph/utils
cp common/graph/utils/type_utils.cc llt/ops/llt_new/stub/common/graph/utils
cp common/register/tensor_assign.cpp llt/ops/llt_new/stub/common/register
cp common/register/scope/scope_pass_registry.cc llt/ops/llt_new/stub/common/register/scope
cp common/register/scope/scope_graph.cc llt/ops/llt_new/stub/common/register/scope
cp common/register/scope/scope_pass.cc llt/ops/llt_new/stub/common/register/scope
cp common/register/scope/scope_pattern.cc llt/ops/llt_new/stub/common/register/scope
cp common/register/scope/scope_util.cc llt/ops/llt_new/stub/common/register/scope
cp framework/domi/common/auth/file_saver.cc llt/ops/llt_new/stub/framework/domi/common/auth
cp framework/domi/common/helper/model_helper.cc llt/ops/llt_new/stub/framework/domi/common/helper
cp framework/domi/common/helper/om_file_helper.cc llt/ops/llt_new/stub/framework/domi/common/helper
cp framework/domi/common/op/attr_value_util.cc llt/ops/llt_new/stub/framework/domi/common/op
cp framework/domi/common/op/ge_op_utils.cc llt/ops/llt_new/stub/framework/domi/common/op
cp framework/domi/parser/common/op_def/ir_pb_converter.cc llt/ops/llt_new/stub/framework/domi/parser/common/op_def
cp framework/domi/parser/common/op_def/operator.cc llt/ops/llt_new/stub/framework/domi/parser/common/op_def
cp framework/domi/parser/common/op_def/defs.cc llt/ops/llt_new/stub/framework/domi/parser/common/op_def
cp framework/domi/parser/common/op_def/fill_op.cc llt/ops/llt_new/stub/framework/domi/parser/common/op_def
cp framework/domi/parser/common/op_def/frameworkop_op.cc llt/ops/llt_new/stub/framework/domi/parser/common/op_def
cp framework/domi/parser/common/op_def/ref_switch_op.cc llt/ops/llt_new/stub/framework/domi/parser/common/op_def
cp framework/domi/parser/common/op_def/shape_n_op.cc llt/ops/llt_new/stub/framework/domi/parser/common/op_def
cp framework/domi/parser/common/op_def/constant_op.cc llt/ops/llt_new/stub/framework/domi/parser/common/op_def
cp framework/domi/parser/common/op_def/variable_op.cc llt/ops/llt_new/stub/framework/domi/parser/common/op_def
cp framework/domi/parser/common/op_def/arg_op.cc llt/ops/llt_new/stub/framework/domi/parser/common/op_def
cp framework/domi/parser/common/op_def/no_op_op.cc llt/ops/llt_new/stub/framework/domi/parser/common/op_def
cp framework/domi/parser/common/op_def/var_is_initialized_op_op.cc llt/ops/llt_new/stub/framework/domi/parser/common/op_def
cp framework/domi/parser/common/op_def/op_schema.cc llt/ops/llt_new/stub/framework/domi/parser/common/op_def
cp framework/domi/parser/common/op_map.cc llt/ops/llt_new/stub/framework/domi/parser/common
cp framework/domi/parser/common/parser_inner_ctx.cc llt/ops/llt_new/stub/framework/domi/parser/common
cp framework/domi/parser/common/acl_graph_parser_util.cc llt/ops/llt_new/stub/framework/domi/parser/common
cp framework/domi/common/fmk_error_codes.cc llt/ops/llt_new/stub/framework/domi/common
cp framework/domi/common/properties_manager.cc llt/ops/llt_new/stub/framework/domi/common
cp framework/domi/common/tbe_kernel_store.cc llt/ops/llt_new/stub/framework/domi/common
cp framework/domi/common/types.cc llt/ops/llt_new/stub/framework/domi/common
cp framework/domi/common/util.cc llt/ops/llt_new/stub/framework/domi/common
cp framework/domi/common/fp16_t.cc llt/ops/llt_new/stub/framework/domi/common
cp framework/domi/common/thread_pool.cc llt/ops/llt_new/stub/framework/domi/common
cp framework/domi/common/context/ctx.cc llt/ops/llt_new/stub/framework/domi/common/context
cp framework/domi/common/convert/pb2json.cc llt/ops/llt_new/stub/framework/domi/common/convert
cp framework/domi/common/model_saver.cc llt/ops/llt_new/stub/framework/domi/common
cp framework/domi/parser/tensorflow/scope/scope_pass_manager.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow/scope
cp framework/domi/graph/passes/variable_format_pass.cc llt/ops/llt_new/stub/framework/domi/graph/passes
cp framework/domi/graph/passes/pass_manager.cc llt/ops/llt_new/stub/framework/domi/graph/passes
cp framework/domi/graph/common/omg_util.cc llt/ops/llt_new/stub/framework/domi/graph/common
cp framework/domi/parser/common/data_op_parser.cc llt/ops/llt_new/stub/framework/domi/parser/common
cp framework/domi/parser/common/op_parser_factory.cc llt/ops/llt_new/stub/framework/domi/parser/common
cp framework/domi/parser/common/parser_factory.cc llt/ops/llt_new/stub/framework/domi/parser/common
cp framework/domi/parser/tensorflow/tensorflow_constant_parser.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/tensorflow_custom_parser_adapter.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/tensorflow_fusion_custom_parser_adapter.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/tensorflow_data_parser.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/tensorflow_fusion_op_parser.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/tensorflow_fusionop_util.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/tensorflow_reshape_parser.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/tensorflow_shape_n_parser.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/tensorflow_squeeze_parser.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/tensorflow_frameworkop_parser.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/tensorflow_util.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/graph_functiondef.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/iterator_fusion_pass.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/graph_optimizer.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/tensorflow_parser.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/tensorflow_variable_v2_parser.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/tensorflow_ref_switch_parser.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/tensorflow_merge_parser.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/tensorflow_enter_parser.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/tensorflow_fill_parser.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/tensorflow_no_op_parser.cc llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/common/pre_checker.cc llt/ops/llt_new/stub/framework/domi/parser/common
cp framework/domi/parser/common/register_tbe.cc llt/ops/llt_new/stub/framework/domi/parser/common
cp framework/domi/model/ge_model.cc llt/ops/llt_new/stub/framework/domi/model
cp framework/domi/common/model_parser/base.cc llt/ops/llt_new/stub/framework/domi/common/model_parser
cp framework/domi/common/ge/tbe_plugin_manager.cc llt/ops/llt_new/stub/framework/domi/common/ge
cp common/graph/operator.cc llt/ops/llt_new/stub/common/graph
cp framework/domi/parser/tensorflow/graph_functiondef.h llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/iterator_fusion_pass.h llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/graph_optimizer.h llt/ops/llt_new/stub/framework/domi/parser/tensorflow
cp framework/domi/parser/tensorflow/graph_insert_trans_op.h llt/ops/llt_new/stub/framework/domi/parser/tensorflow
