/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2020-2020. All rights reserved.
 * Description: ssd detection output op proto h file
 * Author: huawei
 * Create: 2020-8-19
 *
 * @file ssd_detection_output_v2.h
 *
 * @version 1.0
 */

#ifndef GE_OP_SSD_DETECTION_OUTPUT_V2_H
#define GE_OP_SSD_DETECTION_OUTPUT_V2_H

#include "graph/operator_reg.h"

namespace ge {
/**
 * @brief Generates bounding boxes based on "bbox_delta", "score" and "anchors".
 * It is a customized SSD-FD operator.
 *
 * @par Inputs:
 * 3 inputs, including:
 * @li bbox_delta: Region of interests (ROIs) generated by the region proposal
 * network (RPN). A 2D Tensor of type float16 with shape ND(1, N). in SSD-FD model,
 * N equals to 25600
 * @li score: input score, A 2D Tensor of type float16 with shape ND(1, N).
 * in SSD-FD model, N equals to 12800.
 * @li anchors: Absolute variation between the ROIs generated by the RPN and
 * ground truth boxes. A 4D Tensor of type float16 with shape ND (1, 2, N, 4).
 * in SSD-FD model, N equals to 6400.
 *
 * @par Attributes:
 * 10 attributes, including:
 * @li num_classes: class number, datatype: float, default value: 2.
 * @li share_location: a bool var descripe with share location. datatype: bool,.
 * default value: true.
 * @li background_label_id:  datatype: int, default value: 0.
 * @li iou_threshold: nms iou threshold, datatype: float, default value: 0.3
 * @li top_k: max topk value. datatype: int, default value: 5000.
 * @li eta: datatype: float, default value: 1.0.
 * @li variance_encoded_in_target: datatype: bool, default value: false.
 * @li code_type: enmurate type. datatype: int, default value: 2.
 * @li keep_top_k: keep topk number. type. datatype: int, default value: 750.
 * @li confidence_threshold: output boxes's score threshold. datatype: float,
 * default value: 0.01.
 *
 * @par Outputs:
 * 2 outputs, including:
 * @li out_boxnum: output box number, A 2D Tensor of type int32 with shape (1, N).
 * in SSD-FD model, N equals to 8.
 * @li y: output box proposal, A 3D Tensor of type float16 with shape (1, N, 8).
 * in SSD-FD model, N equals to keep_top_k up align 128, (1, 768, 8)
 *
 * @attention Constraints
 * only support Ascend310, support muti-batch N > 1
 */

REG_OP(SSDDetectionOutputV2)
    .INPUT(bbox_delta, TensorType({ DT_FLOAT16 }))
    .INPUT(score, TensorType({ DT_FLOAT16 }))
    .INPUT(anchors, TensorType({ DT_FLOAT16 }))
    .OUTPUT(out_boxnum, TensorType({ DT_INT32 }))
    .OUTPUT(y, TensorType({ DT_FLOAT16 }))
    .ATTR(num_classes, Int, 2)
    .ATTR(share_location, Bool, true)
    .ATTR(background_label_id, Int, 0)
    .ATTR(iou_threshold, Float, 0.3)
    .ATTR(top_k, Int, 5000)
    .ATTR(eta, Float, 1.0)
    .ATTR(variance_encoded_in_target, Bool, false)
    .ATTR(code_type, Int, 2)
    .ATTR(keep_top_k, Int, 750)
    .ATTR(confidence_threshold, Float, 0.01)
    .OP_END_FACTORY_REG(SSDDetectionOutputV2)
}

#endif // GE_OP_DETECTION_OUTPUT_H
